### ISSUE TITLE
time

### ISSUE THREAD

**Issue by ywq2001** [Rachum-thu/DebugBench#3]
How long does it take for you to test the data on the leetcode platform

**Comment by ywq2001** [comment]
It took me about 5 hours to test 1400 pieces of data

**Comment by runchu-tian** [comment]
- Yes, it takes me about the same amount of time.
- This is because LeetCode does not support high-frequency use of their online judge service. We can't change this, but the time invested is worthwhile, as their test cases are almost "golden".
- One possible option could be to use two or three visible test examples, but that would significantly compromise the completeness of the test set and allow some bugs to slip through.
- For most projects, this amount of time is acceptable. It takes around 12 hours to evaluate the entire dataset. If you're conducting a preliminary test, you might consider using a subset to save time.

Thank you for providing feedback on user experience! Feel free to ask more questions.
