### ISSUE TITLE
LeetCode Testing

### ISSUE THREAD

**Issue by SakuraDuck** [Rachum-thu/DebugBench#5]
Hello, I encountered the same issue as issue 4, with the same error message: **leetcode.rest.ApiException: (403) Reason: Forbidden.** Could you please let me know if there's anything else I need to configure besides setting **os.environ['LEETCODE_SESSION']** and **os.environ['CSRF_TOKEN']**?Also, are there any specific details to keep in mind when setting these two environment variables? I would like to understand whether the issue is due to my configuration or a network problem.

**Comment by runchu-tian** [comment]
Thanks for raising the issue.

- For most users, setting the `leetcode_session` and `csrf_token` should be sufficient for the OJ to function properly.
- For more detailed information, you can refer to previous [issue solutions](https://github.com/thunlp/DebugBench/issues/1) like this one.
- If you'd like to determine whether the issue is due to the configuration, feel free to email me. I can provide you with some working tokens so you can test if they work the issue for you.

**Comment by runchu-tian** [comment]
Please feel free to reopen the issue if you still have more problems.
